language: node_js
cache: yarn
script:
  - yarn test
notifications:
  email: false
  slack: interfirm:nQ2iFItAwPADePQlPgmcVE2D#developer
deploy:
  provider: npm
  email: register@interfirm.co.jp
  api_key:
    secure: RjSpLAZgexoMOngboD8gYEd+3yiQls5Ev8WcIhR0Lc3tYYVp3Y15zsz4xf7gi9iZPnQCiLGGcclGVAsbr7l21o2KkaGtrGhWhhz4WuaUbXrbkIOaTNV0Hl2DjUFqovQ4OJhJRmhmKbBjXr8CWScjqNyKRUzEvvwXFnUTYkYBOLNnA3iPFCltAil3oOZfmxxL/tNL/yKuNWgPx5v4m7x/arVIJQIjEl2iIZT3/yF7hM+qxrvblk03YQWjPWEt5jItS+Pfv7L8ExG3KoXUqQBKKlTbIEx6UmNFhw6yxfrKsAnkZAzhHvRbeYzLHQJAjNyOiBTPU3IToTZ0Jazx3Am5DU7VsvW0da47rdxVYUoWseYW5h2s0FC+idSaO9c7JGokolm4r8+3i3WnyTwVJi7Fo10q4TbAM7FgEgWZXVizp2/UTdgAIEZ3VUyK0LXeUKF7ZA6Ewe37824KsZhQ8bHGEtQtpaFJjFspDw8jTef4U8lE6j08yivpxAtL/o34Ccer25iqLnVHKWUNAOko83VcsoWiBOCjdQJFlYJWMNkUD5fShhY53tg+KsjwTRbyx/xwBJDstN0zw+22zSYl9kHu/8pCe7iiQk93uDS25nx8cr91NqA6a9/kLeshKrLphAtWUIlquNmVTKsR2GqKayEzdoUHDeaKjxYKrc/KiYNJDY4=
  on:
    tags: true
