language: node_js
node_js:
  - "6"
before_install:
  - npm install -g yarn
  - yarn
script:
  - yarn test
deploy:
  - provider: script
    script: ./publish.sh
    on:
      branch:
        - release
notifications:
  email: false
